import tempfile
import os
import pandas as pd
from fastapi import APIRouter, File, UploadFile, HTTPException, Body, Query
from pydantic import BaseModel
from app.services.tvae_service import TVAEService
from app.db.mongodb import get_mongo_collection
from app.models.request_models import TrainRequest, GenerateRequest, EvaluateRequest, ExportRequest
from io import StringIO
from typing import List
from datetime import datetime
from time import time
from app.tasks.train_tasks import train_tvae_model
from celery.result import AsyncResult
from app.celery_app import celery_app

router = APIRouter()
tvae_service = TVAEService()


@router.post(
    "/train",
    summary="Train TVAE with optional custom config",
    description="Trains the TVAE model using JSON data and optional configuration like batch_size and epochs.",
    tags=["Training"]
)
def train_model(request: TrainRequest):
    try:
        df = pd.DataFrame(request.data)

        if request.config:
            tvae_service.configure(**request.config)

        tvae_service.train(df)
        return {"message": "Model trained successfully", "config_used": request.config or "default"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post(
    "/train-file",
    summary="Train TVAE from file upload",
    description="Trains the TVAE model using data from an uploaded file. Supports CSV and JSON formats.",
    tags=["Training"]
)
async def train_from_file(
    file: UploadFile = File(...),
    batch_size: int = Query(None),
    epochs: int = Query(10),
    model_path: str = Query(...),
    sample_rows: int = Query(None)
):
    try:
        contents = await file.read()
        df = pd.read_csv(StringIO(contents.decode("utf-8")))

        if sample_rows and df.shape[0] > sample_rows:
            df = df.sample(n=sample_rows, random_state=42)

        if not batch_size:
            if df.shape[0] > 100_000:
                batch_size = 10000
            elif df.shape[0] > 50000:
                batch_size = 5000
            else:
                batch_size = 1000

        tvae_service.configure(batch_size=batch_size, epochs=epochs, verbose=True)

        start = time()
        tvae_service.train(df)
        duration = round(time() - start, 2)

        return {
            "message": f"Model trained and saved successfully",
            "rows_trained": len(df),
            "batch_size": batch_size,
            "epochs": epochs,
            "time_taken_seconds": duration,
            "model_path": model_path
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post(
    "/train-file-celery",
    summary="Train TVAE with Celery",
    description="Asynchronously trains the TVAE model using data from an uploaded file. Supports CSV and JSON formats.",
    tags=["Training"]
)
async def train_file_with_celery(
    file: UploadFile = File(...),
    model_name: str = Query(...),
    batch_size: int = Query(None),
    epochs: int = Query(10),
    sample_rows: int = Query(None),
    verbose: bool = Query(True)
):
    try:
        contents = await file.read()
        df = pd.read_csv(StringIO(contents.decode("utf-8")))

        if sample_rows and df.shape[0] > sample_rows:
            df = df.sample(n=sample_rows)

        if not batch_size:
            if df.shape[0] > 100_000:
                batch_size = 10000
            elif df.shape[0] > 50000:
                batch_size = 5000
            else:
                batch_size = 1000

        config = {"batch_size": batch_size, "epochs": epochs, "verbose": verbose}

        task = train_tvae_model.delay({"rows": df.to_dict(orient="records")}, config, model_name)

        return {"message": "Training task submitted", "task_id": task.id}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post(
    "/generate",
    summary="Generate synthetic data",
    description="Generates synthetic data using the trained TVAE model. Specify the number of rows to generate.",
    tags=["Generation"]
)
def generate_data(request: GenerateRequest):
    try:
        synthetic_df = tvae_service.generate(request.num_rows)
        return synthetic_df.to_dict(orient="records")
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get(
    "/preview",
    summary="Preview synthetic data",
    description="Returns a preview of synthetic data generated by the TVAE model. Specify the number of rows to preview.",
    tags=["Data Management"]
)
def preview_data(num_rows: int = 5):
    try:
        df = tvae_service.preview(num_rows)
        return df.to_dict(orient="records")
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get(
    "/metadata",
    summary="Get training metadata",
    description="Returns metadata about the last training session, including status, timestamp, and configuration used.",
    tags=["Database"]
)
def get_training_metadata():
    return tvae_service.get_training_metadata()


@router.post(
    "/save-to-db",
    summary="Save generated data to MongoDB",
    description="Saves the generated synthetic data to MongoDB. Specify the number of rows to save.",
    tags=["Database"]
)
def save_to_db(request: GenerateRequest):
    try:
        df = tvae_service.generate(request.num_rows)
        collection = get_mongo_collection()
        tvae_service.save_to_mongodb(df, collection)
        return {"message": f"{request.num_rows} rows saved to MongoDB"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post(
    "/save-model",
    summary="Save trained TVAE model",
    description="Saves the trained TVAE model to a specified file path. This allows for later loading and reuse of the model.",
    tags=["Model Management"]
)
def save_model(path: str = Body(..., embed=True)):
    try:
        tvae_service.save_model(path)
        return {"message": f"Model saved to {path}"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post(
    "/load-model",
    summary="Load TVAE model from file",
    description="Loads a previously saved TVAE model from the specified file path. This allows you to reuse a trained model without retraining.",
    tags=["Model Management"]
)
def load_model(path: str = Body(..., embed=True)):
    try:
        tvae_service.load_model(path)
        return {"message": f"Model loaded from {path}"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post(
    "/export",
    summary="Export synthetic data",
    description="Exports synthetic data generated by the TVAE model to a specified format (CSV or JSON). Specify the number of rows and format.",
    tags=["Export"]
)
def export_data(request: ExportRequest):
    try:
        df = tvae_service.generate(request.num_rows)
        with tempfile.NamedTemporaryFile(delete=False, suffix=f".{request.format}") as tmp:
            if request.format == "csv":
                tvae_service.export_to_csv(df, tmp.name)
            elif request.format == "json":
                tvae_service.export_to_json(df, tmp.name)
            else:
                raise HTTPException(status_code=400, detail="Format must be 'csv' or 'json'")
            tmp.seek(0)
            return {"message": "Data exported", "path": tmp.name}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get(
    "/task-status/{task_id}",
    summary="Get task status",
    description="Retrieves the status of a background task by its ID. Returns the current state and any result information.",
    tags=["Tasks"]
)
def get_task_status(task_id: str):
    result = AsyncResult(task_id, app=celery_app)
    return {
        "task_id": task_id,
        "state": result.state,
        "info": result.result
    }
