version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"

  test-api:
    build: ./test-api
    ports:
      - "5000:5000"
