server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: supersecretjwtkey1234567890123456  # exakt som i JwtUtil.java

  cloud:
    gateway:
      routes:
        - id: test-api
          uri: http://test-api:5000
          predicates:
            - Path=/api/test/**
          filters:
            - StripPrefix=1
            
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
