import tempfile
import os
import pandas as pd
from fastapi import APIRouter, File, UploadFile, HTTPException, Body, Query
from pydantic import BaseModel
from app.services.gaussian_service import GaussianCopulaService
from app.db.mongodb import get_mongo_collection
from app.models.request_models import TrainRequest, GenerateRequest, ExportRequest
from io import StringIO
from time import time

router = APIRouter()
gaussian_service = GaussianCopulaService()


@router.post(
    "/train",
    summary="Train GaussianCopula with optional config",
    description="Trains the GaussianCopula model using JSON data and optional configuration.",
    tags=["Training"]
)
def train_model(request: TrainRequest):
    try:
        df = pd.DataFrame(request.data)
        if request.config:
            gaussian_service.configure(**request.config)
        gaussian_service.train(df)
        return {"message": "Model trained successfully", "config_used": request.config or "default"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post(
    "/train-file",
    summary="Train GaussianCopula from file",
    description="Trains the GaussianCopula model using data from an uploaded CSV file.",
    tags=["Training"]
)
async def train_from_file(
    file: UploadFile = File(...),
    model_path: str = Query(...),
    sample_rows: int = Query(None)
):
    try:
        contents = await file.read()
        df = pd.read_csv(StringIO(contents.decode("utf-8")))
        if sample_rows and df.shape[0] > sample_rows:
            df = df.sample(n=sample_rows, random_state=42)
        start = time()
        gaussian_service.train(df)
        duration = round(time() - start, 2)
        return {
            "message": f"Model trained successfully",
            "rows_trained": len(df),
            "time_taken_seconds": duration,
            "model_path": model_path
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post(
    "/generate",
    summary="Generate synthetic data",
    description="Generates synthetic data using the trained GaussianCopula model.",
    tags=["Generation"]
)
def generate_data(request: GenerateRequest):
    try:
        synthetic_df = gaussian_service.generate(request.num_rows)
        return synthetic_df.to_dict(orient="records")
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get(
    "/preview",
    summary="Preview synthetic data",
    description="Returns a preview of synthetic data from the GaussianCopula model.",
    tags=["Data Management"]
)
def preview_data(num_rows: int = 5):
    try:
        df = gaussian_service.preview(num_rows)
        return df.to_dict(orient="records")
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/metadata",
    summary="Get training metadata",
    description="Returns metadata about the GaussianCopula training session.",
    tags=["Database"]
)
def get_training_metadata():
    return gaussian_service.get_training_metadata()


@router.post(
    "/save-to-db",
    summary="Save generated data to MongoDB",
    description="Saves generated synthetic data to MongoDB.",
    tags=["Database"]
)
def save_to_db(request: GenerateRequest):
    try:
        df = gaussian_service.generate(request.num_rows)
        collection = get_mongo_collection()
        gaussian_service.save_to_mongodb(df, collection)
        return {"message": f"{request.num_rows} rows saved to MongoDB"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post(
    "/save-model",
    summary="Save trained GaussianCopula model",
    description="Saves the trained GaussianCopula model to a specified file path.",
    tags=["Model Management"]
)
def save_model(path: str = Body(..., embed=True)):
    try:
        gaussian_service.save_model(path)
        return {"message": f"Model saved to {path}"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post(
    "/load-model",
    summary="Load GaussianCopula model from file",
    description="Loads a previously saved GaussianCopula model from file.",
    tags=["Model Management"]
)
def load_model(path: str = Body(..., embed=True)):
    try:
        gaussian_service.load_model(path)
        return {"message": f"Model loaded from {path}"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post("/export",
    summary="Export synthetic data",
    description="Exports synthetic data generated by the GaussianCopula model.",
    tags=["Export"]
)
def export_data(request: ExportRequest):
    try:
        df = gaussian_service.generate(request.num_rows)
        with tempfile.NamedTemporaryFile(delete=False, suffix=f".{request.format}") as tmp:
            if request.format == "csv":
                gaussian_service.export_to_csv(df, tmp.name)
            elif request.format == "json":
                gaussian_service.export_to_json(df, tmp.name)
            else:
                raise HTTPException(status_code=400, detail="Format must be 'csv' or 'json'")
            tmp.seek(0)
            return {"message": "Data exported", "path": tmp.name}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

